# Stage 1 - Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore TravelAndAccommodationBookingPlatform.sln
RUN dotnet publish TravelAndAccommodationBookingPlatform.WebAPI/TravelAndAccommodationBookingPlatform.WebAPI.csproj -c Release -o /app/publish

# Stage 2 - Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "TravelAndAccommodationBookingPlatform.WebAPI.dll"]
