version: '3.8'

services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TravelBookingDB;User=sa;Password=YourStrong@Passw0rd;
    depends_on:
      - db
    networks:
      - travel-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  mssql_data: