# Use the official ASP.NET Core runtime image as the base
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

# Use the SDK image for building the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore
COPY TravelAndAccommodationBookingPlatform.WebAPI/*.csproj ./TravelAndAccommodationBookingPlatform.WebAPI/
RUN dotnet restore ./TravelAndAccommodationBookingPlatform.WebAPI/TravelAndAccommodationBookingPlatform.WebAPI.csproj

# Copy everything else and build
COPY . .
WORKDIR /src/TravelAndAccommodationBookingPlatform.WebAPI
RUN dotnet publish -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TravelAndAccommodationBookingPlatform.WebAPI.dll"]
